#!/usr/bin/env bash

join -t $'\t' -a 2 -1 1 -2 2 -o 2.1,2.2,2.3,1.2 <(sort categories.txt) <(sort -k2 <(
    brew info --installed | grep 'Cask from' -B1 | grep '==>' | sed 's/==> /cask\t/; s/:/\t/'
    brew info --installed --formula | grep 'on request' -B2 | grep '==>' | sed 's/==> /brew\t/; s/:/\t/'
)) | sort -k1,2 >packages.tsv
